### ISSUE TITLE
Two issues with the button starter kit project

### ISSUE THREAD

**Issue by axb2035** [Jaycar-Electronics/Arduino-Starter-Kit#1]
Hi,

Just completed the button/buzzer project and I believe there are two issues with the info provided.

1. In the diagram the yellow wire should be attached to row 7 of the breadboard not row 8; and
2. In the code `setup()` should be `int Button = 12;` as that is the digital I/O pin that the wire is connected to on the diagram not `int Button= 7;`.

Thanks.

**Comment by Jaycar-Electronics** [comment]
You are correct. Thank you for pointing this out, it has now been amended.

**Comment by James-Randal** [comment]
Its still wrong. may you please QA these things

**Comment by Jaycar-Electronics** [comment]
previous tech didn't read point 1. that has also been corrected in https://github.com/Jaycar-Electronics/Arduino-Starter-Kit/commit/d4743d0164b9e9e1453a73cb1ae1f32e728ef901

Cheers.

**Comment by James-Randal** [comment]
Good on ya Jaycar. Apologise if i sounded a bit blunt. Otherwise i think level of documentation is great, and appreciate the ability to raise issues here on GitHub, and in this case receive quick turnaround.
